name: Build iOS Archive (Flutter, unsigned)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"

      - name: Flutter pub get
        run: flutter pub get

      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Build iOS archive (unsigned)
        run: flutter build ipa --no-codesign

      - name: List archive folder
        run: ls -la build/ios/archive

      - name: Upload XCARCHIVE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner-xcarchive
          path: build/ios/archive/Runner.xcarchive
