name: Build iOS IPA (Flutter, unsigned)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze Flutter code
        run: flutter analyze

      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Install CocoaPods (with mirror for Iran)
        run: |
          sudo gem install cocoapods
          pod repo update

      - name: Install iOS Pods
        run: |
          cd ios
          # استفاده از mirror داخلی برای CocoaPods
          pod install --repo-update --sources=https://gitee.com/mirrors/CocoaPods-Specs.git,https://cdn.cocoapods.org/ --verbose
          cd ..

      - name: Build iOS IPA (unsigned)
        run: flutter build ipa --no-codesign

      - name: Check IPA folder
        run: |
          if [ ! -d "build/ios/ipa" ]; then
            echo "IPA folder does not exist, build failed!"
            exit 1
          fi
          ls -la build/ios/ipa/

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-mobile-ipa
          path: build/ios/ipa/*.ipa
