name: Build iOS IPA (Flutter, unsigned)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"

      - name: Flutter pub get
        run: flutter pub get

      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Build iOS IPA (unsigned)
        run: flutter build ipa --no-codesign --build-dir=build/ios/ipa

      - name: Check IPA
        run: ls -la build/ios/ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-mobile-ipa
          path: build/ios/ipa/**/*.ipa
